services:
    app:
        build: .
        volumes:
            - ./store:/app/store
        ports:
            - 3000:3000
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:3000/livez || exit 1"]
            interval: 30s
            timeout: 5s
            retries: 5
        env_file:
            - ./.env
        environment:
            APP_ENV: ${APP_ENV}

volumes:
    appstore:
