ifneq ($(wildcard ./.env),)
  include .env
  export
else
  env_check = $(shell echo "🟡 WARNING: .env file not found! continue only with exported shell env variables\n\n")
  $(info ${env_check})
endif

.DEFAULT_GOAL := help
SHELL := /bin/bash
MAKEFLAGS += --no-print-directory
GOBIN ?= $(shell go env GOBIN)
DB_PATH ?= database/app.sqlite
SESSION_PATH ?= database/fiber_session.sqlite
GOOSE_CMD ?= go run github.com/pressly/goose/v3/cmd/goose@v3.26.0

##@ Meta
help: ## Show this help with available tasks
	@awk 'BEGIN {FS = ":.*## "}; \
	/^[a-zA-Z0-9_\/-]+:.*## / { printf "  \033[36m%-28s\033[0m %s\n", $$1, $$2 } \
	/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0,5) }' $(MAKEFILE_LIST)

##@ Setup
install: install/go-localize ## Installs deps 🥐 Bun, 🪿 goose, 🛕 templ and  go-localize
	@echo "📦 Installing dependencies"
	@echo "🥐 Installing bun (for tailwindcss)"
	curl -fsSL https://bun.sh/install | bash
	@echo "🌬️ Installing TailwindCSS plugins"
	bun add -D tailwindcss@latest
	bun add -D daisyui@latest
	bun add -D @tailwindcss/typography
	@echo "🪿 installing goose"
	go install github.com/pressly/goose/v3/cmd/goose@latest
	@echo "🛕 installing Templ"
	go install github.com/a-h/templ/cmd/templ@latest

install/go-localize: ## Install go-localize CLI
	@echo " installing go-localize"
	go install github.com/m1/go-localize@latest

##@ Code Quality
fmt: ## Run go fmt
	go fmt ./...

vet: fmt ## Run go vet (after fmt)
	go vet ./...

lint: vet ## Alias for vet

##@ Frontend
tailwind/build: ## Build Tailwind CSS
	@echo "🌬️ Generating Tailwind CSS styles..."
	bun x @tailwindcss/cli -i ./styles/global.css -o ./public/global.css --minify

tailwind/watch: ## Watch Tailwind CSS
	@echo "🌬️ Watching for Tailwind CSS changes..."
	bun x @tailwindcss/cli -i ./styles/global.css -o ./public/global.css --minify --watch

templ/build: tailwind/build ## Generate Templ files (depends on tailwind)
	@echo "🛕 Generating Templ files..."
	templ generate

templ/watch: ## Watch Templ
	@echo "🛕 Watching for Templ changes..."
	templ generate --watch -v

locales/build: ## Build locales with go-localize
	@echo "  Building locales"
	go-localize -input locales -output internal/lib/localize
	$(MAKE) locales/normalize

locales/normalize: ## Remove volatile timestamp from generated locales file
	@awk 'skip { skip = 0; next } /^\/\/ This file was generated by robots at$$/ { skip = 1; next } { print }' internal/lib/localize/localize.go > internal/lib/localize/localize.go.tmp
	@mv internal/lib/localize/localize.go.tmp internal/lib/localize/localize.go

##@ AI Docs
ai/templ-sync: ## Refresh templ LLM upstream snapshot and metadata
	@echo "🤖 Refreshing templ LLM docs snapshot..."
	./scripts/update-templ-llms.sh

##@ Build & Run
build: templ locales/build ## Build Go binary with fts5
	@echo "📦 Building"
	go build -tags fts5 -o bin/app cmd/app/main.go

start: ## Start the built binary
	@echo "👟 Starting the app..."
	bin/app

run: templ ## Run via go run (generates Templ first)
	@echo "👟 Running app..."
	go run -tags fts5 cmd/app/main.go

air/watch: ## Run in dev mode with air (installs if missing)
	@if command -v air > /dev/null; then \
	    air; \
	else \
	    read -p "Install air? [Y/n] " choice; \
	    if [ "$$choice" != "n" ] && [ "$$choice" != "N" ]; then \
	        go install github.com/cosmtrek/air@latest; \
	        air; \
	    else \
	        echo "You chose not to install air. Exiting..."; \
	        exit 1; \
	    fi; \
	fi

dev: docker/up ## Start infra, then tailwind/watch, templ/watch, and air/watch
	$(MAKE) -j3 tailwind/watch templ/watch air/watch

##@ Tests
test: ## Run all tests
	@echo "Testing all"
	go test ./cmd/... ./internal/... ./tests/...

test/race: ## Run all tests with race detector
	@echo "Testing all with race detector"
	go test -race ./cmd/... ./internal/... ./tests/...

test/coverage: ## Coverage
	@mkdir -p coverage
	@rm -f coverage/all.out coverage/all.filtered.out coverage/summary.filtered.txt coverage/pkg_coverage.txt coverage/service_pkg_coverage.txt
	@printf "\033[36m🧪 Running unified coverage (cmd + internal + integration tests)...\033[0m\n"
	@go test ./cmd/... ./internal/... ./tests/... -covermode=atomic -coverpkg=./cmd/...,./internal/... -coverprofile=coverage/all.out
	@printf "\033[35m🧹 Filtering generated files from coverage profile...\033[0m\n"
	@awk 'NR==1 || ($$0 !~ /internal\/lib\/localize\// && $$0 !~ /_templ\.go:/)' coverage/all.out > coverage/all.filtered.out
	@go tool cover -func=coverage/all.filtered.out > coverage/summary.filtered.txt
	@awk 'NR>1 {split($$1,a,":"); file=a[1]; block=$$1; stmts=$$2+0; cnt=$$3+0; if (!(block in seen)) {seen[block]=1; blockStmts[block]=stmts; blockFile[block]=file} if (cnt>0) blockCovered[block]=1} END {for (b in seen) {pkg=blockFile[b]; sub(/\/[^\/]+$$/,"",pkg); total[pkg]+=blockStmts[b]; if (blockCovered[b]) covered[pkg]+=blockStmts[b]} for (p in total) {pct=(total[p]>0)?(100*covered[p]/total[p]):0; printf "%06.2f%% %4d/%-4d %s\n", pct, covered[p], total[p], p}}' coverage/all.filtered.out | sort -n > coverage/pkg_coverage.txt
	@awk '$$3 ~ /^miconsul\/internal\/service\// {print}' coverage/pkg_coverage.txt > coverage/service_pkg_coverage.txt
	@printf "\033[32m✅ Coverage total: %s (generated files excluded)\033[0m\n" "$$(awk '/^total:/{print $$NF}' coverage/summary.filtered.txt)"
	@printf "\033[33m📉 Lowest covered packages (filtered):\033[0m\n"
	@awk 'NR<=15 {print}' coverage/pkg_coverage.txt

test/coverage/html: test/coverage ## Generate HTML coverage report
	go tool cover -html=coverage/all.filtered.out -o coverage/all.filtered.html
	@echo "Coverage HTML generated at coverage/all.filtered.html"
	@xdg-open coverage/all.filtered.html >/dev/null 2>&1 || \
		python3 -m webbrowser coverage/all.filtered.html >/dev/null 2>&1 || \
		echo "Open coverage/all.filtered.html manually in your browser"

test/coverage/service-leaderboard: test/coverage ## Show service package coverage leaderboard
	@echo "Service package coverage leaderboard (filtered):"
	@cat coverage/service_pkg_coverage.txt

test/coverage/gate-global-65: ## Fail if unified filtered coverage is < 65%
	@test -f coverage/summary.filtered.txt || (echo "Run make test/coverage first" && exit 1)
	@pct=$$(awk '/^total:/{gsub("%","",$$NF); print $$NF}' coverage/summary.filtered.txt); \
	if awk "BEGIN {exit !($$pct >= 65)}"; then \
		echo "✅ Unified filtered coverage gate passed: $$pct% (>= 65%)"; \
	else \
		echo "❌ Unified filtered coverage gate failed: $$pct% (< 65%)"; \
		exit 1; \
	fi

test/coverage/gate-service-floor-65: ## Fail if any service package coverage is < 65%
	@test -f coverage/service_pkg_coverage.txt || (echo "Run make test/coverage first" && exit 1)
	@violations=$$(awk '$$1+0 < 65 {print}' coverage/service_pkg_coverage.txt); \
	if [ -n "$$violations" ]; then \
		echo "❌ Service floor gate failed (< 65%):"; \
		printf "%s\n" "$$violations"; \
		exit 1; \
	fi; \
	echo "✅ Service floor gate passed (all internal/service/* >= 65%)"

##@ Cleanup
clean: ## Remove build artifacts
	@echo "Cleaning builds..."
	rm -f bin/*

##@ Database & Migrations
db/create: ## Create DB (migrations run by app/seed bootstrap)
	@echo "🧱 DB file is created automatically by migrations/bootstrap"

db/delete: ## Delete DB (interactive confirmation)
	@printf "\033[33m⚠️ Delete DB (this is destructive)? [y/N]\033[0m "; \
	read choice; \
	if [ "$$choice" != "y" ] && [ "$$choice" != "Y" ]; then \
		echo "🛑 Exiting..."; exit 1; \
	else \
		echo "🗑️ Deleting $(DB_PATH) and $(SESSION_PATH)..."; \
		rm -f "$(DB_PATH)" "$(SESSION_PATH)"; \
	fi

db/setup: ## Recreate DB, apply migrations, and seed
	@$(MAKE) db/delete
	@$(MAKE) db/create
	@$(MAKE) db/seed

db/reset: db/setup ## Alias for full DB reset (drop/migrate/seed)

db/dump_schema: ## Dump DB schema
	sqlite3 store/app.sqlite3 .schema > goose/schema.sql

migrations/apply: ## Apply migrations with goose
	@echo "🪿 Running migrations with momma goose"
	$(GOOSE_CMD) up

db/migrate: migrations/apply ## Alias for migrations/apply

db/seed: ## Run DB seeds (baseline + randomized bulk)
	@echo "🌱 Running seed command"
	@go run -tags fts5 cmd/seed/main.go

.PHONY: migrations/create/%
migrations/create/%: ## Create a migration file: make migrations/create/add_column_to_table
	$(GOOSE_CMD) create $* sql

migrations/status: ## Show migrations status
	$(GOOSE_CMD) status

migrations/rollback: ## Roll back last migration
	$(GOOSE_CMD) down

migrations/redo: ## Redo last migration
	$(GOOSE_CMD) redo

##@ Docker
docker/up: ## Start docker infra services (without app)
	@echo " Docker infra services up"
	docker compose up -d lgtm

docker/dev: ## Start all docker services including app
	@echo " All docker services up"
	docker compose up -d

docker/detached: ## docker compose up -d
	@echo " Docker up detached"
	docker compose up -d

docker/down: ## docker compose down
	@echo " Docker down"
	docker compose down

docker/logs: ## Follow logs for all docker services
	@echo " Docker all service logs"
	docker compose logs -f

docker/app-logs: ## Follow app container logs
	@echo " Docker app logs"
	docker compose logs app -f

docker/lgtm-logs: ## Follow LGTM stack logs
	@echo " Docker LGTM logs"
	docker compose logs lgtm -f

docker/build: ## Rebuild the app image
	docker compose up --no-deps --build app

##@ Observability
obs/load: ## Run continuous synthetic traffic (~40 RPM total)
	$(MAKE) obs/load/medium

obs/load/light: ## Run lighter synthetic traffic (~20 RPM total)
	PUBLIC_RPM=12 PROTECTED_RPM=8 ./scripts/obs_load.sh

obs/load/medium: ## Run medium synthetic traffic (~40 RPM total)
	PUBLIC_RPM=24 PROTECTED_RPM=16 ./scripts/obs_load.sh

obs/load/heavy: ## Run heavier synthetic traffic (~80 RPM total)
	PUBLIC_RPM=48 PROTECTED_RPM=32 ./scripts/obs_load.sh

load/test: ## Run authenticated oha load test (30s, 30 concurrency)
	./scripts/load_test.sh


.PHONY: help install install/go-localize fmt vet lint \
	tailwind tailwind/watch templ templ/watch locales/build \
	locales/normalize \
	ai/templ-sync \
	build start run air/watch dev \
	test test/race clean \
	test/coverage test/coverage/html test/coverage/service-leaderboard \
	test/coverage/gate-global-65 test/coverage/gate-service-floor-65 \
	db/create db/delete db/setup db/reset db/dump_schema db/seed \
	migrations/apply migrate migrations/create migrations/status migrations/rollback migrations/redo \
	docker/up docker/dev docker/detached docker/down docker/logs docker/app-logs docker/lgtm-logs docker/build \
	obs/load obs/load/light obs/load/medium obs/load/heavy load/test
