ifneq ($(wildcard ./.env),)
  include .env
  export
else
  env_check = $(shell echo "🟡 WARNING: .env file not found! continue only with exported shell env variables\n\n")
  $(info ${env_check})
endif

.DEFAULT_GOAL := help
SHELL := /bin/bash
MAKEFLAGS += --no-print-directory
GOBIN ?= $(shell go env GOBIN)
DB_PATH ?= database/app.sqlite
SESSION_PATH ?= database/fiber_session.sqlite
GOOSE_CMD ?= go run github.com/pressly/goose/v3/cmd/goose@v3.26.0

##@ Meta
help: ## Show this help with available tasks
	@awk 'BEGIN {FS = ":.*## "}; \
	/^[a-zA-Z0-9_\/-]+:.*## / { printf "  \033[36m%-28s\033[0m %s\n", $$1, $$2 } \
	/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0,5) }' $(MAKEFILE_LIST)

##@ Setup
install: install/go-localize ## Installs deps 🥐 Bun, 🪿 goose, 🛕 templ and  go-localize
	@echo "📦 Installing dependencies"
	@echo "🥐 Installing bun (for tailwindcss)"
	curl -fsSL https://bun.sh/install | bash
	@echo "🌬️ Installing TailwindCSS plugins"
	bun add -D tailwindcss@latest
	bun add -D daisyui@latest
	bun add -D @tailwindcss/typography
	@echo "🪿 installing goose"
	go install github.com/pressly/goose/v3/cmd/goose@latest
	@echo "🛕 installing Templ"
	go install github.com/a-h/templ/cmd/templ@latest

install/go-localize: ## Install go-localize CLI
	@echo " installing go-localize"
	go install github.com/m1/go-localize@latest

##@ Code Quality
fmt: ## Run go fmt
	go fmt ./...

vet: fmt ## Run go vet (after fmt)
	go vet ./...

lint: vet ## Alias for vet

##@ Frontend
tailwind/build: ## Build Tailwind CSS
	@echo "🌬️ Generating Tailwind CSS styles..."
	bun x @tailwindcss/cli -i ./styles/global.css -o ./public/global.css --minify

tailwind/watch: ## Watch Tailwind CSS
	@echo "🌬️ Watching for Tailwind CSS changes..."
	bun x @tailwindcss/cli -i ./styles/global.css -o ./public/global.css --minify --watch

templ/build: tailwind/build ## Generate Templ files (depends on tailwind)
	@echo "🛕 Generating Templ files..."
	templ generate

templ/watch: ## Watch Templ
	@echo "🛕 Watching for Templ changes..."
	templ generate --watch -v

locales/build: ## Build locales with go-localize
	@echo "  Building locales"
	go-localize -input locales -output internal/lib/localize
	$(MAKE) locales/normalize

locales/normalize: ## Remove volatile timestamp from generated locales file
	@awk 'skip { skip = 0; next } /^\/\/ This file was generated by robots at$$/ { skip = 1; next } { print }' internal/lib/localize/localize.go > internal/lib/localize/localize.go.tmp
	@mv internal/lib/localize/localize.go.tmp internal/lib/localize/localize.go

##@ AI Docs
ai/templ-sync: ## Refresh templ LLM upstream snapshot and metadata
	@echo "🤖 Refreshing templ LLM docs snapshot..."
	./scripts/update-templ-llms.sh

##@ Build & Run
build: templ locales/build ## Build Go binary with fts5
	@echo "📦 Building"
	go build -tags fts5 -o bin/app cmd/app/main.go

start: ## Start the built binary
	@echo "👟 Starting the app..."
	bin/app

run: templ ## Run via go run (generates Templ first)
	@echo "👟 Running app..."
	go run -tags fts5 cmd/app/main.go

air/watch: ## Run in dev mode with air (installs if missing)
	@if command -v air > /dev/null; then \
	    air; \
	else \
	    read -p "Install air? [Y/n] " choice; \
	    if [ "$$choice" != "n" ] && [ "$$choice" != "N" ]; then \
	        go install github.com/cosmtrek/air@latest; \
	        air; \
	    else \
	        echo "You chose not to install air. Exiting..."; \
	        exit 1; \
	    fi; \
	fi

dev: docker/up ## Start infra, then tailwind/watch, templ/watch, and air/watch
	$(MAKE) -j3 tailwind/watch templ/watch air/watch

##@ Tests
test: ## Run all tests
	@echo "Testing all"
	go test ./...

test/race: ## Run all tests with race detector
	@echo "Testing all with race detector"
	go test -race ./...

test/v: ## Verbose tests
	@echo "Testing all verbose"
	go test ./... -v

test/unit: ## Run unit tests
	@echo "Testing unit"
	go test -race ./internal/...

test/unit/c: ## Run unit tests
	@echo "Testing unit"
	go test ./internal/... -race -coverprofile=coverage/unit_c.out && go tool cover -func=coverage/unit_c.out

test/unit/v: ## Run unit tests in verbose mode
	@echo "Testing units --verbose"
	go test -v -race ./internal/...

test/integration: ## Run integration tests
	@echo "Testing integration"
	go test -v ./tests/... -coverprofile=coverage/int_c.out

test/coverage: ## Coverage
	mkdir -p coverage
	rm -f coverage/c.out
	go test ./... -covermode=atomic -coverprofile=coverage/c.out
	go tool cover -func=coverage/c.out > coverage/summary.txt
	@tail -n 1 coverage/summary.txt

test/coverage/html: test/coverage ## Generate HTML coverage report
	go tool cover -html=coverage/c.out -o coverage/c.html
	@echo "Coverage HTML generated at coverage/c.html"
	@xdg-open coverage/c.html >/dev/null 2>&1 || \
		python3 -m webbrowser coverage/c.html >/dev/null 2>&1 || \
		echo "Open coverage/c.html manually in your browser"

##@ Test Coverage
cover:
	go test ./internal/... -covermode=atomic -coverpkg=./internal/... -coverprofile=coverage/c.out
	go tool cover -func=coverage/c.out

cover/html: cover
	go tool cover -html=coverage/c.out -o coverage/c.html
	@echo "Open coverage.html in your browser"
	google-chrome coverage/c.html

cover/missing: cover
	@awk -F '[: ,]+' 'NR>1 && $$NF==0 {printf "%s:%s-%s\n",$$1,$$2,$$4}' coverage.out | sort

##@ Cleanup
clean: ## Remove build artifacts
	@echo "Cleaning builds..."
	rm -f bin/*

##@ Database & Migrations
db/create: ## Create DB (migrations run by app/seed bootstrap)
	@echo "🧱 DB file is created automatically by migrations/bootstrap"

db/delete: ## Delete DB (interactive confirmation)
	@printf "\033[33m⚠️ Delete DB (this is destructive)? [y/N]\033[0m "; \
	read choice; \
	if [ "$$choice" != "y" ] && [ "$$choice" != "Y" ]; then \
		echo "🛑 Exiting..."; exit 1; \
	else \
		echo "🗑️ Deleting $(DB_PATH) and $(SESSION_PATH)..."; \
		rm -f "$(DB_PATH)" "$(SESSION_PATH)"; \
	fi

db/setup: ## Recreate DB, apply migrations, and seed
	@$(MAKE) db/delete
	@$(MAKE) db/create
	@$(MAKE) db/seed

db/reset: db/setup ## Alias for full DB reset (drop/migrate/seed)

db/dump_schema: ## Dump DB schema
	sqlite3 store/app.sqlite3 .schema > goose/schema.sql

migrations/apply: ## Apply migrations with goose
	@echo "🪿 Running migrations with momma goose"
	$(GOOSE_CMD) up

db/migrate: migrations/apply ## Alias for migrations/apply

db/seed: ## Run DB seeds (baseline + randomized bulk)
	@echo "🌱 Running seed command"
	@go run -tags fts5 cmd/seed/main.go

.PHONY: migrations/create/%
migrations/create/%: ## Create a migration file: make migrations/create/add_column_to_table
	$(GOOSE_CMD) create $* sql

migrations/status: ## Show migrations status
	$(GOOSE_CMD) status

migrations/rollback: ## Roll back last migration
	$(GOOSE_CMD) down

migrations/redo: ## Redo last migration
	$(GOOSE_CMD) redo

##@ Docker
docker/up: ## Start docker infra services (without app)
	@echo " Docker infra services up"
	docker compose up -d lgtm

docker/dev: ## Start all docker services including app
	@echo " All docker services up"
	docker compose up -d

docker/detached: ## docker compose up -d
	@echo " Docker up detached"
	docker compose up -d

docker/down: ## docker compose down
	@echo " Docker down"
	docker compose down

docker/logs: ## Follow logs for all docker services
	@echo " Docker all service logs"
	docker compose logs -f

docker/app-logs: ## Follow app container logs
	@echo " Docker app logs"
	docker compose logs app -f

docker/lgtm-logs: ## Follow LGTM stack logs
	@echo " Docker LGTM logs"
	docker compose logs lgtm -f

docker/build: ## Rebuild the app image
	docker compose up --no-deps --build app

##@ Observability
obs/load: ## Run continuous synthetic traffic (~40 RPM total)
	$(MAKE) obs/load/medium

obs/load/light: ## Run lighter synthetic traffic (~20 RPM total)
	PUBLIC_RPM=12 PROTECTED_RPM=8 ./scripts/obs_load.sh

obs/load/medium: ## Run medium synthetic traffic (~40 RPM total)
	PUBLIC_RPM=24 PROTECTED_RPM=16 ./scripts/obs_load.sh

obs/load/heavy: ## Run heavier synthetic traffic (~80 RPM total)
	PUBLIC_RPM=48 PROTECTED_RPM=32 ./scripts/obs_load.sh

load/test: ## Run authenticated oha load test (30s, 30 concurrency)
	./scripts/load_test.sh


.PHONY: help install install/go-localize fmt vet lint \
	tailwind tailwind/watch templ templ/watch locales/build \
	locales/normalize \
	ai/templ-sync \
	build start run air/watch dev \
	test test/unit test/integration clean \
	test/race test/v test/unit/v test/unit/c test/coverage test/coverage/html \
	db/create db/delete db/setup db/reset db/dump_schema db/seed \
	migrations/apply migrate migrations/create migrations/status migrations/rollback migrations/redo \
	docker/up docker/dev docker/detached docker/down docker/logs docker/app-logs docker/lgtm-logs docker/build \
	obs/load obs/load/light obs/load/medium obs/load/heavy load/test
