// Code generated by go-localize; DO NOT EDIT.
// This file was generated by robots at
// 2024-05-17 18:36:43.138244334 -0600 CST m=+0.001064897

package localize

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

var localizations = map[string]string{
	"en-US.btn.back":                                     "Back",
	"en-US.btn.cancel":                                   "Cancel",
	"en-US.btn.confirm":                                  "Confirm",
	"en-US.btn.login":                                    "Login",
	"en-US.btn.logout":                                   "Logout",
	"en-US.btn.new_patient":                              "Add new",
	"en-US.btn.reschedule":                               "Reschedule",
	"en-US.btn.save":                                     "Save",
	"en-US.btn.signup":                                   "Signup",
	"en-US.btn.update":                                   "Update",
	"en-US.btn.view_all":                                 "View all",
	"en-US.btn.view_appointments":                        "View appointments",
	"en-US.nav.appointments":                             "Appointments",
	"en-US.nav.clinics":                                  "Clinics",
	"en-US.nav.exp_rev":                                  "Expents/Revenue",
	"en-US.nav.next_5":                                   "Next 5",
	"en-US.nav.patients":                                 "Patients",
	"en-US.nav.this_month":                               "This month",
	"en-US.nav.this_week":                                "This week",
	"en-US.nav.today":                                    "Today",
	"en-US.str.address":                                  "Address",
	"en-US.str.address_city":                             "City",
	"en-US.str.address_country":                          "Country",
	"en-US.str.address_desc":                             "Street name and number, city, state or province, country (optional) and zip code.",
	"en-US.str.address_state_province":                   "State / Province",
	"en-US.str.address_street":                           "Street address",
	"en-US.str.address_zip_code":                         "Zip / Postal Code",
	"en-US.str.age":                                      "Age",
	"en-US.str.all_appointments":                         "All appointments",
	"en-US.str.all_revenue":                              "All revenue",
	"en-US.str.appointment_today":                        "Appt. Today",
	"en-US.str.appointments":                             "Appointments",
	"en-US.str.are_you_sure":                             "Are you sure?",
	"en-US.str.back":                                     "Back",
	"en-US.str.background":                               "Background",
	"en-US.str.background_ph":                            "Medical history, previous deceases and episodes, triggers, family status, etc...",
	"en-US.str.canceled":                                 "canceled",
	"en-US.str.change":                                   "Change",
	"en-US.str.clinics":                                  "Clinics",
	"en-US.str.confirmed":                                "confirmed",
	"en-US.str.cover_photo":                              "Cover photo",
	"en-US.str.create_new_patient":                       "New",
	"en-US.str.date":                                     "Date",
	"en-US.str.decreased_by":                             "Decreased by",
	"en-US.str.edit_patient":                             "Edit patient",
	"en-US.str.email_address":                            "Email address",
	"en-US.str.exp_rev":                                  "Expents/Revenue",
	"en-US.str.family_history":                           "Family history",
	"en-US.str.family_history_ph":                        "Relevant information about family background",
	"en-US.str.first_name":                               "First name",
	"en-US.str.increased_by":                             "Increased by",
	"en-US.str.last_appointment":                         "Last appointment ",
	"en-US.str.last_name":                                "Last name",
	"en-US.str.location":                                 "Location",
	"en-US.str.login":                                    "Login",
	"en-US.str.logout":                                   "Logout",
	"en-US.str.medical_profile":                          "Medical profile",
	"en-US.str.medical_profile_desc":                     "This information is private, it will only be shared with the appropiate personel.",
	"en-US.str.new_patient":                              "New patient",
	"en-US.str.notes":                                    "Notes",
	"en-US.str.notes_ph":                                 "Other information considered relevant or related",
	"en-US.str.notifications":                            "Notifications",
	"en-US.str.notifications_about":                      "Notify about",
	"en-US.str.notifications_appointment_lifecycle":      "Create/Cancel/Reschedule appointments",
	"en-US.str.notifications_appointment_lifecycle_desc": "Notify when a new appointment is created, canceled or rescheduled.",
	"en-US.str.notifications_desc":                       "We'll let the patient know about important changes to their appointments, but you can pick what they are notified about.",
	"en-US.str.notifications_via":                        "Send notifications via",
	"en-US.str.ocupation":                                "Ocupation",
	"en-US.str.or_drag_and_drop":                         "or drag and drop",
	"en-US.str.patients":                                 "Patients",
	"en-US.str.pending":                                  "pending",
	"en-US.str.personal_info":                            "Personal information",
	"en-US.str.personal_info_desc":                       "Use a permanent email address where you can receive mail.",
	"en-US.str.profile_pic":                              "Profile Pic",
	"en-US.str.rescheduled":                              "rescheduled",
	"en-US.str.revenue_month":                            "Revenue this month",
	"en-US.str.save":                                     "Save",
	"en-US.str.signup":                                   "Signup",
	"en-US.str.stats":                                    "Statistics",
	"en-US.str.up_to_10mb":                               "up to 10MB",
	"en-US.str.upload_file":                              "Upload a file",
	"es-MX.btn.back":                                     "Regresar",
	"es-MX.btn.cancel":                                   "Cancelar",
	"es-MX.btn.confirm":                                  "Confirmar",
	"es-MX.btn.login":                                    "Iniciar sesion",
	"es-MX.btn.logout":                                   "Salir",
	"es-MX.btn.new_patient":                              "Nuevo",
	"es-MX.btn.reschedule":                               "Reagendar",
	"es-MX.btn.save":                                     "Guardar",
	"es-MX.btn.signup":                                   "Registrate",
	"es-MX.btn.update":                                   "Actualizar",
	"es-MX.btn.view_all":                                 "Ver todo",
	"es-MX.btn.view_appointments":                        "Ver citas",
	"es-MX.nav.appointments":                             "Citas",
	"es-MX.nav.clinics":                                  "Consultorios",
	"es-MX.nav.exp_rev":                                  "Contabilidad",
	"es-MX.nav.next_5":                                   "Siguientes 5",
	"es-MX.nav.patients":                                 "Pacientes",
	"es-MX.nav.this_month":                               "Mi mes",
	"es-MX.nav.this_week":                                "Mi semana",
	"es-MX.nav.today":                                    "Mi dia",
	"es-MX.str.address":                                  "Direccion",
	"es-MX.str.address_city":                             "Ciudad",
	"es-MX.str.address_country":                          "Pais",
	"es-MX.str.address_desc":                             "Calle, numero exterior, ciudad, estado, pais (opcional) y codigo postal.",
	"es-MX.str.address_state":                            "Estado",
	"es-MX.str.address_street":                           "Calle y Numero",
	"es-MX.str.address_zip_code":                         "Codigo postal",
	"es-MX.str.age":                                      "Edad",
	"es-MX.str.all_appointments":                         "Todas las citas",
	"es-MX.str.all_revenue":                              "Contabilidad",
	"es-MX.str.appointment_today":                        "Cita Hoy",
	"es-MX.str.appointments":                             "Citas",
	"es-MX.str.are_you_sure":                             "Estas seguro?",
	"es-MX.str.back":                                     "Regresar",
	"es-MX.str.background":                               "Antedecentes",
	"es-MX.str.background_ph":                            "Historial medico, enfermedades previas, episodios pasados, detonantes, situacion familiar, etc...",
	"es-MX.str.canceled":                                 "cancelada",
	"es-MX.str.change":                                   "Cambiar",
	"es-MX.str.clinics":                                  "Consultorios",
	"es-MX.str.confirmed":                                "confirmada",
	"es-MX.str.cover_photo":                              "Archivos adjuntos",
	"es-MX.str.create_new_patient":                       "Agregar un paciente nuevo",
	"es-MX.str.date":                                     "fecha",
	"es-MX.str.decreased_by":                             "Decremento de",
	"es-MX.str.edit_patient":                             "Editar paciente",
	"es-MX.str.email_address":                            "Correo electronico",
	"es-MX.str.exp_rev":                                  "Gastos/Ganancias",
	"es-MX.str.family_history":                           "Historial familiar",
	"es-MX.str.family_history_ph":                        "Informacion relevante en los antecedentes familiares",
	"es-MX.str.first_name":                               "Nombres",
	"es-MX.str.increased_by":                             "Incremento de",
	"es-MX.str.last_appointment":                         "Ultima cita",
	"es-MX.str.last_name":                                "Apellidos",
	"es-MX.str.location":                                 "Ubicacion",
	"es-MX.str.login":                                    "Iniciar sesion",
	"es-MX.str.logout":                                   "Cerrar sesion",
	"es-MX.str.medical_profile":                          "Historial medico",
	"es-MX.str.medical_profile_desc":                     "Esta informacion es privada, se compartira solo con personal autorizado.",
	"es-MX.str.new_patient":                              "Paciente nuevo",
	"es-MX.str.notes":                                    "Notas",
	"es-MX.str.notes_ph":                                 "Otra informacion considerada relevante o relacionada",
	"es-MX.str.notifications":                            "Notificaciones",
	"es-MX.str.notifications_about":                      "Enviar notificaciones sobre",
	"es-MX.str.notifications_appointment_lifecycle":      "Al crear, cancelar o reagendar citas",
	"es-MX.str.notifications_appointment_lifecycle_desc": "Notificar al paciente cuando creo, cancelo o reagendo citas.",
	"es-MX.str.notifications_desc":                       "Notificaremos al paciente sobre cambios importantes a su cita, tambien puedes escoger a traves de que plataforma sera notificado",
	"es-MX.str.notifications_via":                        "Enviar notificaciones por:",
	"es-MX.str.ocupation":                                "Ocupacion",
	"es-MX.str.or_drag_and_drop":                         "o arrastralo aqui",
	"es-MX.str.patients":                                 "Pacientes",
	"es-MX.str.pending":                                  "pendiente",
	"es-MX.str.personal_info":                            "Informacion personal",
	"es-MX.str.personal_info_desc":                       "Usa una direccion de correo en la que puedas recibir notificaciones.",
	"es-MX.str.profile_pic":                              "Foto de perfil",
	"es-MX.str.rescheduled":                              "reagendada",
	"es-MX.str.revenue_month":                            "Ganancias del mes",
	"es-MX.str.save":                                     "Guardar",
	"es-MX.str.signup":                                   "Registrate",
	"es-MX.str.stats":                                    "Datos mensuales",
	"es-MX.str.up_to_10mb":                               "hasta 10MB",
	"es-MX.str.upload_file":                              "Sube un archivo",
}

type Replacements map[string]interface{}

type Localizer struct {
	Locale         string
	FallbackLocale string
	Localizations  map[string]string
}

func New(locale string, fallbackLocale string) *Localizer {
	t := &Localizer{Locale: locale, FallbackLocale: fallbackLocale}
	t.Localizations = localizations
	return t
}

func (t Localizer) SetLocales(locale, fallback string) Localizer {
	t.Locale = locale
	t.FallbackLocale = fallback
	return t
}

func (t Localizer) SetLocale(locale string) Localizer {
	t.Locale = locale
	return t
}

func (t Localizer) SetFallbackLocale(fallback string) Localizer {
	t.FallbackLocale = fallback
	return t
}

func (t Localizer) GetWithLocale(locale, key string, replacements ...*Replacements) string {
	str, ok := t.Localizations[t.getLocalizationKey(locale, key)]
	if !ok {
		str, ok = t.Localizations[t.getLocalizationKey(t.FallbackLocale, key)]
		if !ok {
			return key
		}
	}

	// If the str doesn't have any substitutions, no need to
	// template.Execute.
	if strings.Index(str, "}}") == -1 {
		return str
	}

	return t.replace(str, replacements...)
}

func (t Localizer) Get(key string, replacements ...*Replacements) string {
	str := t.GetWithLocale(t.Locale, key, replacements...)
	return str
}

func (t Localizer) getLocalizationKey(locale string, key string) string {
	return fmt.Sprintf("%v.%v", locale, key)
}

func (t Localizer) replace(str string, replacements ...*Replacements) string {
	b := &bytes.Buffer{}
	tmpl, err := template.New("").Parse(str)
	if err != nil {
		return str
	}

	replacementsMerge := Replacements{}
	for _, replacement := range replacements {
		for k, v := range *replacement {
			replacementsMerge[k] = v
		}
	}

	err = template.Must(tmpl, err).Execute(b, replacementsMerge)
	if err != nil {
		return str
	}
	buff := b.String()
	return buff
}
